package targets

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// TargetCursor is the identifier for the Cursor target.
const TargetCursor = "cursor"

// CursorTarget symlinks .cursor/rules/<name>.mdc → ~/.scribe/skills/<name>/.cursor.mdc.
// The .cursor.mdc is generated by WriteToStore from SKILL.md frontmatter.
// Because multiple projects can symlink the same source, updating the store
// propagates to every project automatically.
type CursorTarget struct {
	// WorkDir is the project root. Defaults to os.Getwd() if empty.
	WorkDir string
}

func (t CursorTarget) Name() string { return TargetCursor }

func (t CursorTarget) Install(skillName, canonicalDir string) ([]string, error) {
	workDir := t.WorkDir
	if workDir == "" {
		var err error
		workDir, err = os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("getwd: %w", err)
		}
	}

	rulesDir := filepath.Join(workDir, ".cursor", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return nil, fmt.Errorf("create cursor rules dir: %w", err)
	}

	src := filepath.Join(canonicalDir, ".cursor.mdc")
	if _, err := os.Stat(src); err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("skill %q has no .cursor.mdc in store (missing SKILL.md?)", skillName)
		}
		return nil, fmt.Errorf("check cursor rule for %q: %w", skillName, err)
	}

	link := filepath.Join(rulesDir, skillName+".mdc")
	if err := replaceSymlink(link, src); err != nil {
		return nil, fmt.Errorf("symlink cursor/%s: %w", skillName, err)
	}
	return []string{link}, nil
}

// generateMDC builds a Cursor .mdc file from a SKILL.md.
// Maps `description` from frontmatter, strips frontmatter from body.
func generateMDC(skillMD []byte) []byte {
	description := extractFrontmatterField(skillMD, "description")

	var sb strings.Builder
	sb.WriteString("---\n")
	if description != "" {
		sb.WriteString("description: ")
		sb.WriteString(description)
		sb.WriteString("\n")
	}
	sb.WriteString("alwaysApply: false\n")
	sb.WriteString("---\n\n")
	sb.Write(stripFrontmatter(skillMD))
	return []byte(sb.String())
}

func extractFrontmatterField(content []byte, key string) string {
	lines := strings.SplitN(string(content), "\n", -1)
	inFrontmatter := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "---" {
			if !inFrontmatter {
				inFrontmatter = true
				continue
			}
			break
		}
		if !inFrontmatter {
			continue
		}
		k, v, ok := strings.Cut(trimmed, ":")
		if !ok || strings.TrimSpace(k) != key {
			continue
		}
		v = strings.TrimSpace(v)
		v = strings.Trim(v, `"'`)
		return v
	}
	return ""
}

func stripFrontmatter(content []byte) []byte {
	s := string(content)
	if !strings.HasPrefix(s, "---") {
		return content
	}
	rest := s[3:]
	idx := strings.Index(rest, "\n---")
	if idx == -1 {
		return content
	}
	return []byte(strings.TrimLeft(rest[idx+4:], "\n"))
}

func isSkillMD(path string) bool {
	return strings.EqualFold(filepath.Base(path), "SKILL.md")
}
