package tools

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// toolCursor is the identifier for the Cursor tool.
const toolCursor = "cursor"

// CursorTool symlinks .cursor/rules/<name>.mdc → ~/.scribe/skills/<name>/.cursor.mdc.
// The .cursor.mdc is generated by WriteToStore from SKILL.md frontmatter.
// Because multiple projects can symlink the same source, updating the store
// propagates to every project automatically.
type CursorTool struct {
	// WorkDir is the project root. Defaults to os.Getwd() if empty.
	WorkDir string
}

func (t CursorTool) Name() string { return toolCursor }

func (t CursorTool) Detect() bool {
	home, err := os.UserHomeDir()
	if err != nil {
		return false
	}
	_, err = os.Stat(filepath.Join(home, ".cursor"))
	return err == nil
}

func (t CursorTool) Install(skillName, canonicalDir string) ([]string, error) {
	workDir, err := t.resolveWorkDir()
	if err != nil {
		return nil, err
	}

	// Generate .cursor.mdc from SKILL.md in the store.
	skillMDPath := filepath.Join(canonicalDir, "SKILL.md")
	skillMD, err := os.ReadFile(skillMDPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("skill %q has no SKILL.md in store", skillName)
		}
		return nil, fmt.Errorf("read SKILL.md for %q: %w", skillName, err)
	}

	mdcPath := filepath.Join(canonicalDir, ".cursor.mdc")
	mdc := generateMDC(skillMD)
	if err := os.WriteFile(mdcPath, mdc, 0o644); err != nil {
		return nil, fmt.Errorf("write .cursor.mdc for %q: %w", skillName, err)
	}

	rulesDir := filepath.Join(workDir, ".cursor", "rules")

	// Slugify for safety — bare names pass through unchanged,
	// but this protects against any residual slashes.
	mdcName := SlugifyRegistry(skillName) + ".mdc"

	link := filepath.Join(rulesDir, mdcName)
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return nil, fmt.Errorf("create cursor rules dir: %w", err)
	}
	if err := replaceSymlink(link, mdcPath); err != nil {
		return nil, fmt.Errorf("symlink cursor/%s: %w", skillName, err)
	}
	return []string{link}, nil
}

func (t CursorTool) Uninstall(skillName string) error {
	workDir, err := t.resolveWorkDir()
	if err != nil {
		return err
	}
	mdcName := SlugifyRegistry(skillName) + ".mdc"
	link := filepath.Join(workDir, ".cursor", "rules", mdcName)
	if err := os.Remove(link); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("remove cursor/%s: %w", skillName, err)
	}
	return nil
}

func (t CursorTool) SkillPath(skillName string) (string, error) {
	workDir, err := t.resolveWorkDir()
	if err != nil {
		return "", err
	}
	mdcName := SlugifyRegistry(skillName) + ".mdc"
	return filepath.Join(workDir, ".cursor", "rules", mdcName), nil
}

func (t CursorTool) CanonicalTarget(canonicalDir string) (string, bool) {
	return filepath.Join(canonicalDir, ".cursor.mdc"), true
}

// generateMDC builds a Cursor .mdc file from a SKILL.md.
// Maps `description` from frontmatter, strips frontmatter from body.
func generateMDC(skillMD []byte) []byte {
	description := extractFrontmatterField(skillMD, "description")

	var sb strings.Builder
	sb.WriteString("---\n")
	if description != "" {
		sb.WriteString("description: ")
		sb.WriteString(description)
		sb.WriteString("\n")
	}
	sb.WriteString("alwaysApply: false\n")
	sb.WriteString("---\n\n")
	sb.Write(stripFrontmatter(skillMD))
	return []byte(sb.String())
}

func extractFrontmatterField(content []byte, key string) string {
	lines := strings.SplitN(string(content), "\n", -1)
	inFrontmatter := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "---" {
			if !inFrontmatter {
				inFrontmatter = true
				continue
			}
			break
		}
		if !inFrontmatter {
			continue
		}
		k, v, ok := strings.Cut(trimmed, ":")
		if !ok || strings.TrimSpace(k) != key {
			continue
		}
		v = strings.TrimSpace(v)
		v = strings.Trim(v, `"'`)
		return v
	}
	return ""
}

// resolveWorkDir returns t.WorkDir if set, otherwise falls back to os.Getwd().
func (t CursorTool) resolveWorkDir() (string, error) {
	if t.WorkDir != "" {
		return t.WorkDir, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("getwd: %w", err)
	}
	return wd, nil
}

func stripFrontmatter(content []byte) []byte {
	s := string(content)
	if !strings.HasPrefix(s, "---") {
		return content
	}
	rest := s[3:]
	idx := strings.Index(rest, "\n---")
	if idx == -1 {
		return content
	}
	return []byte(strings.TrimLeft(rest[idx+4:], "\n"))
}
