package tools_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Naoray/scribe/internal/tools"
)

var testFiles = []tools.SkillFile{
	{Path: "SKILL.md", Content: []byte(`---
name: deploy
description: "Artistfy deployment workflow"
license: MIT
---

## Deploy

Run the deploy script.
`)},
	{Path: "scripts/deploy.sh", Content: []byte("#!/bin/sh\necho deploying\n")},
}

func setup(t *testing.T) (canonicalDir string) {
	t.Helper()
	t.Setenv("HOME", t.TempDir())
	dir, err := tools.WriteToStore("deploy", testFiles)
	if err != nil {
		t.Fatalf("WriteToStore: %v", err)
	}
	return dir
}

func TestWriteToStore(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir, err := tools.WriteToStore("deploy", testFiles)
	if err != nil {
		t.Fatalf("WriteToStore: %v", err)
	}

	// Source files written
	if _, err := os.Stat(filepath.Join(dir, "SKILL.md")); err != nil {
		t.Error("SKILL.md not in store")
	}
	if _, err := os.Stat(filepath.Join(dir, "scripts", "deploy.sh")); err != nil {
		t.Error("scripts/deploy.sh not in store")
	}
	// .cursor.mdc is NOT generated by WriteToStore (generated by CursorTool.Install)
	if _, err := os.Stat(filepath.Join(dir, ".cursor.mdc")); !os.IsNotExist(err) {
		t.Error(".cursor.mdc should not be in store after WriteToStore")
	}
}

func TestClaudeInstall(t *testing.T) {
	canonicalDir := setup(t)

	tool := tools.ClaudeTool{}
	paths, err := tool.Install("deploy", canonicalDir)
	if err != nil {
		t.Fatalf("Install: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 symlink path, got %d", len(paths))
	}

	// Link resolves to SKILL.md file, not the directory.
	resolved, err := os.Readlink(paths[0])
	if err != nil {
		t.Fatalf("Readlink: %v", err)
	}
	wantTarget := filepath.Join(canonicalDir, "SKILL.md")
	if resolved != wantTarget {
		t.Errorf("symlink points to %q, want %q", resolved, wantTarget)
	}

	// Content accessible through the symlink.
	content, err := os.ReadFile(paths[0])
	if err != nil {
		t.Fatalf("read through symlink: %v", err)
	}
	if len(content) == 0 {
		t.Error("SKILL.md content empty through symlink")
	}
}

func TestClaudeInstallReplaces(t *testing.T) {
	canonicalDir := setup(t)
	tool := tools.ClaudeTool{}

	// Install twice — second should replace the first without error.
	if _, err := tool.Install("deploy", canonicalDir); err != nil {
		t.Fatalf("first Install: %v", err)
	}
	if _, err := tool.Install("deploy", canonicalDir); err != nil {
		t.Fatalf("second Install: %v", err)
	}
}

func TestCursorInstall(t *testing.T) {
	canonicalDir := setup(t)
	workDir := t.TempDir()

	tool := tools.CursorTool{WorkDir: workDir}
	paths, err := tool.Install("deploy", canonicalDir)
	if err != nil {
		t.Fatalf("Install: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("expected 1 symlink path, got %d", len(paths))
	}

	// Symlink points into the store
	resolved, err := os.Readlink(paths[0])
	if err != nil {
		t.Fatalf("Readlink: %v", err)
	}
	expectedSrc := filepath.Join(canonicalDir, ".cursor.mdc")
	if resolved != expectedSrc {
		t.Errorf("symlink points to %q, want %q", resolved, expectedSrc)
	}

	// Content accessible through the symlink
	mdc, err := os.ReadFile(paths[0])
	if err != nil {
		t.Fatalf("read mdc through symlink: %v", err)
	}
	content := string(mdc)
	if !strings.Contains(content, "description: Artistfy deployment workflow") {
		t.Errorf("MDC missing description:\n%s", content)
	}
	if !strings.Contains(content, "alwaysApply: false") {
		t.Errorf("MDC missing alwaysApply:\n%s", content)
	}
	if !strings.Contains(content, "## Deploy") {
		t.Errorf("MDC missing body:\n%s", content)
	}
	if strings.Contains(content, "license: MIT") {
		t.Errorf("MDC should not contain SKILL.md frontmatter")
	}
}

func TestClaudeDetect(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	tool := tools.ClaudeTool{}
	if tool.Detect() {
		t.Error("should not detect claude when ~/.claude doesn't exist")
	}

	os.MkdirAll(filepath.Join(home, ".claude"), 0o755)
	if !tool.Detect() {
		t.Error("should detect claude when ~/.claude exists")
	}
}

func TestClaudeUninstall(t *testing.T) {
	canonicalDir := setup(t)
	tool := tools.ClaudeTool{}

	if _, err := tool.Install("deploy", canonicalDir); err != nil {
		t.Fatalf("Install: %v", err)
	}
	if err := tool.Uninstall("deploy"); err != nil {
		t.Fatalf("Uninstall: %v", err)
	}

	home, _ := os.UserHomeDir()
	link := filepath.Join(home, ".claude", "skills", "deploy")
	if _, err := os.Lstat(link); !os.IsNotExist(err) {
		t.Error("expected symlink to be removed after uninstall")
	}
}

func TestCursorDetect(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	tool := tools.CursorTool{}
	if tool.Detect() {
		t.Error("should not detect cursor when ~/.cursor doesn't exist")
	}

	os.MkdirAll(filepath.Join(home, ".cursor"), 0o755)
	if !tool.Detect() {
		t.Error("should detect cursor when ~/.cursor exists")
	}
}

func TestCursorUninstall(t *testing.T) {
	canonicalDir := setup(t)
	workDir := t.TempDir()
	tool := tools.CursorTool{WorkDir: workDir}

	if _, err := tool.Install("deploy", canonicalDir); err != nil {
		t.Fatalf("Install: %v", err)
	}
	if err := tool.Uninstall("deploy"); err != nil {
		t.Fatalf("Uninstall: %v", err)
	}

	link := filepath.Join(workDir, ".cursor", "rules", "deploy.mdc")
	if _, err := os.Lstat(link); !os.IsNotExist(err) {
		t.Error("expected symlink to be removed after uninstall")
	}
}

func TestSlugifyRegistry(t *testing.T) {
	cases := []struct {
		input string
		want  string
	}{
		{"ArtistfyHQ/team-skills", "ArtistfyHQ-team-skills"},
		{"vercel/skills", "vercel-skills"},
		{"owner/repo", "owner-repo"},
	}
	for _, c := range cases {
		t.Run(c.input, func(t *testing.T) {
			got := tools.SlugifyRegistry(c.input)
			if got != c.want {
				t.Errorf("SlugifyRegistry(%q) = %q, want %q", c.input, got, c.want)
			}
		})
	}
}

func TestWriteToStoreFlat(t *testing.T) {
	t.Setenv("HOME", t.TempDir())

	dir, err := tools.WriteToStore("deploy", testFiles)
	if err != nil {
		t.Fatalf("WriteToStore: %v", err)
	}

	// Verify path is flat — no registry slug subdirectory.
	storeDir, _ := tools.StoreDir()
	expected := filepath.Join(storeDir, "deploy")
	if dir != expected {
		t.Errorf("store dir = %q, want %q", dir, expected)
	}

	// Files exist.
	if _, err := os.Stat(filepath.Join(dir, "SKILL.md")); err != nil {
		t.Error("SKILL.md not in store")
	}
}

func TestCursorInstallBareName(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	workDir := t.TempDir()

	dir, err := tools.WriteToStore("deploy", testFiles)
	if err != nil {
		t.Fatalf("WriteToStore: %v", err)
	}

	tool := tools.CursorTool{WorkDir: workDir}
	paths, err := tool.Install("deploy", dir)
	if err != nil {
		t.Fatalf("Install: %v", err)
	}

	// Bare name passes through slugify unchanged.
	expectedLink := filepath.Join(workDir, ".cursor", "rules", "deploy.mdc")
	if paths[0] != expectedLink {
		t.Errorf("symlink path = %q, want %q", paths[0], expectedLink)
	}
}
